version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sms_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3304
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
